name: Upload to S3 on PR Merge

on:
  push:
    branches:
      - main
    paths:
      - 'data/students.csv'

env:
  AWS_REGION: us-east-1

jobs:
  upload-to-s3:
    environment: AWS-Credentials  # 👈 this is the key
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload students.csv to S3
        run: aws s3 cp data/students.csv s3://sso-user-creation-s3/students.csv
